Repository macuna3/classProject, pull requests merged in 2019-05, with the labels that each got.

#2 Client Web
  WebClient/src/Cliente.java
Labels: Cliente

#3 Server Files
  WebServer/src/java/Agencia.java
  WebServer/src/java/Reserva.java
  WebServer/src/java/Titular.java
Labels: Servidor

#5 Reserva.java
  WebServer/src/java/Reserva.java
Labels: Servidor

#7 interfaz principal
  WebClient/web/Cancelar.html
  WebClient/web/assets/header_bg.jpg
  WebClient/web/assets/iphone.png
  WebClient/web/index.html
Labels: Interfaz

#6 Titular
  WebServer/src/java/Titular.java
Labels: Servidor

#10 añadiendo estilos a la web
  WebClient/web/css/main.css
Labels: Interfaz

#8 Añadir funciones a la app web
  WebClient/web/Modificar.html
  WebClient/web/VerRerserva.html
Labels: Interfaz

#9 Código fuente del Cliente
  WebClient/src/Cliente.java
Labels: Cliente

#11 Borrar una variable que no se usa
  WebClient/web/index.html
Labels: Arreglos
